scraper:
  headless: true
  timeout: 30

courses_to_monitor:
  - code: "CS 403"
    name: "Công Nghệ Phần Mềm"
    url: "https://courses.duytan.edu.vn/Sites/Home_ChuongTrinhDaoTao.aspx?p=home_listcoursedetail&courseid=100&timespan=92&t=s"
  
  - code: "HIS 364"
    name: "Lịch Sử Việt Nam"
    url: "https://courses.duytan.edu.vn/Sites/Home_ChuongTrinhDaoTao.aspx?p=home_listcoursedetail&courseid=1860&timespan=92&t=s"
  
  - code: "ENG 217"
    name: "English Communication"
    url: "https://courses.duytan.edu.vn/Sites/Home_ChuongTrinhDaoTao.aspx?p=home_listcoursedetail&courseid=1076&timespan=92&t=s"
 
  - code: "ENG "
    name: "English Communication"
    url: "https://courses.duytan.edu.vn/Sites/Home_ChuongTrinhDaoTao.aspx?p=home_listcoursedetail&courseid=1074&timespan=92&t=s"
telegram:
  bot_token: "${TELEGRAM_BOT_TOKEN}"
  chat_ids:
    - 5337351935

database:
  path: "data/courses.db"

monitoring:
  interval_minutes: 5

logging:
  level: "INFO"
  file: "logs/monitor.log"
